---
apiVersion: tailscale.com/v1alpha1
kind: Ingress
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  backend:
    service:
      name: actualbudget
      port:
        number: 5006
  tailscale:
    hostname: actualbudget
  tls:
    httpsMode: true
